# Generated by Django 3.2.4 on 2021-06-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='blockchain_network_name',
            field=models.CharField(max_length=200, verbose_name='Название Сети'),
        ),
    ]
